# Generated by Django 5.2.6 on 2025-09-05 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.round')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('penalty_goals', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('result', models.CharField(blank=True, choices=[('win', 'Win'), ('draw', 'Draw'), ('loss', 'Loss')], max_length=10, null=True)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_teams', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_matches', to='teams.team')),
            ],
            options={
                'verbose_name': 'Match Team',
                'verbose_name_plural': 'Match Teams',
                'unique_together': {('match', 'team')},
            },
        ),
    ]
