# Generated by Django 5.2.6 on 2025-09-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterModelOptions(
            name='matchteam',
            options={'verbose_name': 'Equipo en Partido', 'verbose_name_plural': 'Equipos en Partidos'},
        ),
    ]
