# Generated by Django 5.2.6 on 2025-09-20 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_alter_match_options_alter_matchteam_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchteam",
            name="goals",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="matchteam",
            name="penalty_goals",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
