# Generated by Django 5.2.6 on 2025-09-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team', 'jersey_number'], 'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['tournament_category', 'name'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
    ]
