# Generated by Django 5.2.6 on 2025-09-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_player_options_alter_team_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="oficio",
            field=models.CharField(
                blank=True,
                help_text="Oficio o profesión (Ej: Ingeniero, Lic. Trabajo Social)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="promo",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Año de la promoción a la que perteneció (ej. 1987, 2015)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
