# Generated by Django 5.2.6 on 2025-09-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_player_oficio_player_promo_player_telefono"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="telefono",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="oficio",
            new_name="profession",
        ),
    ]
