# Generated by Django 5.2.6 on 2025-09-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchevent',
            options={'verbose_name': 'Evento del Partido', 'verbose_name_plural': 'Eventos del Partido'},
        ),
    ]
