"""
Django settings for Don Bosco Cup project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Importando Librerias para caonfiguracion base del proyecto
import json
import os
from datetime import timedelta
from pathlib import Path

from decouple import config
from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured

# Configuracion de Messages
MESSAGE_TAGS = {
    messages.DEBUG: "alert-info",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = *********

# Application definition

DJANGO_APPS = (
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "rest_framework",
    "rest_framework.authtoken",  # Necesario para manejar tokens
    "rest_framework_simplejwt",
    # CORS Headers
    "corsheaders",
)

# Aplicaciones de Terceros
THIRD_PARTY_APPS = (
    "crispy_forms",
    "crispy_bootstrap5",
    "dj_rest_auth",
    "django_extensions",  # Para comandos como show_urls
)

LOCAL_APPS = (
    "tournaments",
    "teams",
    "matches",
    "events",
    "project",  # Para la configuración del admin
)

# Aplicaciones Locales
INSTALLED_APPS = THIRD_PARTY_APPS + DJANGO_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Para archivos estáticos
    "corsheaders.middleware.CorsMiddleware",  # 🚀 Agrega esta línea aquí
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# AUTH_USER_MODEL = "users.User"  # Comentado para usar el modelo de usuario por defecto

SITE_ID = 1  # Asegúrate de que esto esté configurado

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "es-es"

TIME_ZONE = "America/Argentina/Salta"

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = "/admin/"
LOGIN_URL = "/admin/login/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
# Aquí defines el directorio donde Django colocará los archivos estáticos en producción
STATIC_ROOT = os.path.join(
    BASE_DIR, "staticfiles"
)  # Debe ser diferente de STATICFILES_DIRS

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

CSRF_TRUSTED_ORIGINS = [
    "https://brava.okarol.com",
    "http://127.0.0.1",
    "http://localhost",
    "http://localhost:5174",
]

# Configuración de CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Permitir peticiones desde React
    "http://127.0.0.1:3000",
    "http://localhost:5174",
]

# Si quieres permitir todas las solicitudes desde cualquier origen (no recomendado en producción)
# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True  # Permitir que se envíen cookies y autenticación

# Para PERMITIR LA CONFIGURACION DE LOS USUARIOS
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Usa la base de datos para almacenar sesiones
SESSION_COOKIE_HTTPONLY = True  # Protege la cookie de sesión
SESSION_COOKIE_SECURE = False  # Cambia a True en producción con HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = (
    False  # Permite que la sesión persista después de cerrar el navegador
)

# REST_USE_JWT = True  # Activa JWT en dj-rest-auth

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # Expira en 1 día
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# Configuración simplificada para el proyecto Don Bosco Cup
# Usamos python-decouple para manejar variables de entorno

# settings.py
ACCOUNT_USERNAME_REQUIRED = False  # No obligar a username
ACCOUNT_EMAIL_VERIFICATION = "none"  # No verificar email por correo
