[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_django = "django"
known_first_party = ["tournaments", "teams", "matches", "events", "project"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]
skip_glob = ["*/migrations/*"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
ignore_missing_imports = true
follow_imports = "silent"
strict_optional = false
pretty = true
show_error_codes = true
show_column_numbers = true

[[tool.mypy.overrides]]
module = [
    "django.*",
    "rest_framework.*",
    "dj_rest_auth.*",
    "crispy_forms.*",
    "corsheaders.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "tournaments.*",
    "teams.*",
    "matches.*",
    "events.*",
]
disallow_untyped_defs = false
