# Generated by Django 5.2.6 on 2025-09-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase_name",
                    models.CharField(
                        help_text="e.g., League, Knockout, Group Stage", max_length=100
                    ),
                ),
                (
                    "phase_type",
                    models.CharField(
                        choices=[("league", "League"), ("knockout", "Knockout")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Phase",
                "verbose_name_plural": "Phases",
                "ordering": ["tournament_category", "id"],
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Salesian Tournament 2024", max_length=100
                    ),
                ),
                ("year", models.CharField(help_text="Tournament year", max_length=4)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "verbose_name": "Tournament",
                "verbose_name_plural": "Tournaments",
                "ordering": ["-year", "name"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_name",
                    models.CharField(
                        help_text="e.g., Matchday 1, Semifinal, Final", max_length=100
                    ),
                ),
                (
                    "round_number",
                    models.CharField(help_text="e.g., 1, SF, F", max_length=20),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="tournaments.phase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Round",
                "verbose_name_plural": "Rounds",
                "ordering": ["phase", "id"],
            },
        ),
        migrations.CreateModel(
            name="TournamentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        help_text="e.g., Class of 2019, Under-16", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Category",
                "verbose_name_plural": "Tournament Categories",
                "ordering": ["tournament", "category_name"],
                "unique_together": {("tournament", "category_name")},
            },
        ),
        migrations.AddField(
            model_name="phase",
            name="tournament_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="tournaments.tournamentcategory",
            ),
        ),
    ]
