# Generated by Django 5.2.6 on 2025-09-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['tournament_category', 'id'], 'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['phase', 'id'], 'verbose_name': 'Ronda', 'verbose_name_plural': 'Rondas'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-year', 'name'], 'verbose_name': 'Torneo', 'verbose_name_plural': 'Torneos'},
        ),
        migrations.AlterModelOptions(
            name='tournamentcategory',
            options={'ordering': ['tournament', 'category_name'], 'verbose_name': 'Categoría del Torneo', 'verbose_name_plural': 'Categorías del Torneo'},
        ),
    ]
