# Generated by Django 5.2.6 on 2025-09-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_alter_phase_options_alter_round_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournamentcategory",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="tournamentcategory",
            name="start_date",
        ),
    ]
